---
- name: Install & Start docker
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: install requirements
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      update_cache: yes

  - name: add docker key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: install docker repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present

  - name: install docker
    apt:
      pkg:
      - docker-ce=5:19.03.15~3-0~ubuntu-bionic
      - python3-pip


  - name: install docker-py
    pip:
      name: docker

  - name: adding user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes
