version: '3.3'
services:
  post_db:
    image: mongo:${MNGOVER}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UIVER}
    ports:
      - ${PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${PSTVER}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${CMNTVER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
